### ISSUE TITLE
Increase screen brightness if it's too dark [4-8h]

### ISSUE THREAD

**Issue by sladomic** [literacyapp-org/literacyapp-android#140]

**Comment by jo-elimu** [comment]
@sladomic See https://github.com/literacyapp-org/literacyapp-ui/blob/master/app/src/main/AndroidManifest.xml#L6 and https://github.com/literacyapp-org/literacyapp-ui/blob/master/app/src/main/java/org/literacyapp/ui/UiBroadcastReceiver.java#L40
