### ISSUE TITLE
Improve face detection of dark skin children - Implement face detection settings [4-8h]

### ISSUE THREAD

**Issue by sladomic** [literacyapp-org/literacyapp-android#146]
- [x] use another classifier (lbp vs haar)
- [x] remove the eye detection
- [x] change some settings for Viola Jones (search rectangle size)
- [x] histogram equalization
- [ ] try algorithm described in the paper (see comment) --> new issue #225 
- [ ] ~~use another classifier model (maybe there's one trained on children)~~
- [ ] ~~train our own face detection classifier~~

**Comment by sladomic** [comment]
http://cradpdf.drdc-rddc.gc.ca/PDFS/unc160/p800532_A1b.pdf I will try this algorithm to improve the performance of face detection

"First, the image is converted to the hue, saturation, and value colour scheme (HSV). The algorithm is then applied to the value channel. Our algorithm alters the value raising the spread and intensities of dark pixels while maintaining the difference at the midrange. The new image is converted to grayscale and the Haar detector is used to search for faces."

**Comment by jo-elimu** [comment]
@sladomic Great!

So what we should do now is test _all_ 2^3 = 8 variations of these adjustments, right?:
1. Eye detection on/off
2. With/without Haar improvement
3. Default/high camera light exposure
