### ISSUE TITLE
Only save StudentImage if the face is inside the frame [4-8h]

### ISSUE THREAD

**Issue by nya-elimu** [literacyapp-org/literacyapp-android#148]

**Comment by jo-elimu** [comment]
@sladomic @schaemik What if a face is detected while outside frame?

**Comment by sladomic** [comment]
2 options
1. We don't search outside the frame (faster). If nothing is detected we would need to signal them (voice, overlay) what they need to do.
2. We search the whole screen (slower). If one face is found for example left of the frame, we could add an arrow which points to the frame.
