### ISSUE TITLE
Save background images in test mode

### ISSUE THREAD

**Issue by sladomic** [literacyapp-org/literacyapp-android#163]
- save background images all 100ms
- if test mode enabled

**Comment by jo-elimu** [comment]
How is test mode enabled?

**Comment by sladomic** [comment]
How do you want it? You don't have any Preferences/Settings until now. 
1. Either it's hardcoded
2. or we need to introduce a SettingsActivity
3. or we can try with a config file

**Comment by jo-elimu** [comment]
@sladomic Hardcoded is fine 👍
