### ISSUE TITLE
Add immersive mode

### ISSUE THREAD

**Issue by nya-elimu** [literacyapp-org/literacyapp-android#19]
https://developer.android.com/training/system-ui/immersive.html

[--- This issue is linked with an Asana task
# attachments [device-2016-01-21-101225.png](https://app.asana.com/app/asana/-/download_asset?asset_id=82569344016143), [device-2016-01-21-101300.png](https://app.asana.com/app/asana/-/download_asset?asset_id=82569344016145)
# url https://app.asana.com/0/0/82230613068757/f

---[aa]

**Comment by nya-elimu** [comment]
Jo, he realizado unas pruebas aquí te dejo unos screenshots y me comentas que opinas.

[--- Commented from Asana.com
#commenter Adrián Pérez Morales
---[aa]

**Comment by jo-elimu** [comment]
![82569344016143 cumnswfxqok0ndrj8cxb_height640](https://cloud.githubusercontent.com/assets/1451036/12477153/3ffd2b08-c02e-11e5-9c83-eb1551710aed.png)

**Comment by jo-elimu** [comment]
Adrián, why does it appear in orange color?

**Comment by jo-elimu** [comment]
https://www.youtube.com/watch?v=cBi8fjv90E4

**Comment by jo-elimu** [comment]
![screen shot 2016-01-22 at 11 53 11](https://cloud.githubusercontent.com/assets/1451036/12508855/c9983508-c0fe-11e5-8151-e0d6193372b0.png)
