### ISSUE TITLE
Remove ActionBar

### ISSUE THREAD

**Issue by jo-elimu** [literacyapp-org/literacyapp-android#23]
Normally, the ActionBar only contains text. So since the children don't know how to read text, it doesn't make sense to waste screen real estate with the ActionBar.

**Comment by nya-elimu** [comment]
![screenshot_2016-01-05-15-51-39](https://cloud.githubusercontent.com/assets/15718174/12509104/726b665e-c100-11e5-88f5-04c5f2ecadfa.png)

**Comment by jo-elimu** [comment]
![screenshot_2016-01-22-15-50-16](https://cloud.githubusercontent.com/assets/1451036/12513791/02107e10-c120-11e5-9400-5e88486f7486.png)
