### ISSUE TITLE
Delete StudentImages if the featureExtraction can't be run

### ISSUE THREAD

**Issue by sladomic** [literacyapp-org/literacyapp-android#236]
Delete StudentImages if the featureExtraction can't be run because the files (student images) are missing on the sdcard

**Comment by jo-elimu** [comment]
The feature extraction might fail because of these 2 different reasons, right?:

1. Image missing on SD card
2. Image exists, but extraction failed.

**Comment by sladomic** [comment]
Now the StudentImageCollectionEvent and all connected StudentImages and StudentImageFeatures will be deleted if

1) a file is missing
2) feature extraction for a StudentImage fails

@jogrimst I just delete them in the db but not the files itself. Should I also delete the files or keep them for debugging?
