### ISSUE TITLE
Create wireframes for first screens

### ISSUE THREAD

**Issue by jo-elimu** [literacyapp-org/literacyapp-android#28]
What are the very first screens the child will se after opening the application?

Create wireframes. Use English as example language (we'll translate to Arabic later).
1. Add wireframes to Google Drive
2. Export as image files and upload to InVision prototype.

**Comment by jogrimst** [comment]
https://docs.google.com/presentation/d/1xoRgGxxlBIONnAxFYJ26Sw78sIuMs2oyeSThs1CBtak/edit#slide=id.gfe5ceb25a_0_2

**Comment by jo-elimu** [comment]
https://invis.io/GT5QC02PK

**Comment by jo-elimu** [comment]
Wireframes in Google Drive: https://drive.google.com/drive/folders/0B6UZAYGIWxA-SWl4b0Y0U0R2NXM
