### ISSUE TITLE
Add custom logging utility

### ISSUE THREAD

**Issue by jo-elimu** [literacyapp-org/literacyapp-android#31]
We don't want to use android.util.Log for logging because we need to be able to deactivate logging in production (see http://developer.android.com/intl/es/tools/publishing/preparing.html#publishing-configure)

See http://stackoverflow.com/questions/2446248/remove-all-debug-logging-calls-before-publishing-are-there-tools-to-do-this
1. Add custom Logging utility as alternative to android.util.Log
2. It should be possible to deactivate logging during production (after release to Google Play).

Related to #21

**Comment by jogrimst** [comment]
It should be possible to deactivate logging during production (after release to Google Play).

**Comment by jogrimst** [comment]
See this in relation to #33

**Comment by jo-elimu** [comment]
See this in relation to #21

**Comment by adrygll2** [comment]
https://github.com/JakeWharton/timber
